# Generated by Django 4.1 on 2022-12-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverId', models.CharField(editable=False,
                 max_length=255, primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, null=True, max_length=3)),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
