# Generated by Django 4.1 on 2022-12-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverId', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('driverRef', models.CharField(max_length=255)),
                ('number', models.IntegerField(max_length=11)),
                ('code', models.CharField(max_length=3)),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
